# Generated by Django 5.1.6 on 2025-02-26 19:06

import app.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('encrypted_message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('sender_ip', models.GenericIPAddressField(default=app.models.get_ip)),
                ('file_attachment', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('bandwidth_used', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
